
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author setti
 */
public class CustomerCheckin extends javax.swing.JFrame {
Connection con =null;
    Statement st=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form CustomerCheckin
     */
    public CustomerCheckin() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Gowtham@123");
        }catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
        }
          gowtham();      
    }
    public void gowtham(){
    try {
        pst=con.prepareStatement("select Room_Number from room where   Room_Type=? and Bed_Type=? and status=?");
        
           pst.setString(1, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
           pst.setString(2, combobedtype.getItemAt(combobedtype.getSelectedIndex()));
           pst.setString(3,"Not Started" );
           rs=pst.executeQuery();
           comboroomnumber.removeAllItems();
           while(rs.next()){
               comboroomnumber.addItem(rs.getString("Room_Number"));
           }
           pst=con.prepareStatement("select price from room where Room_Number=?");
           pst.setString(1, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
           rs=pst.executeQuery();
           if(rs.next())
               txtprice.setText(rs.getString("price"));
    } catch (SQLException ex) {
        Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
    }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtaadhar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combobedtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboroomnumber = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\java project\\images\\close.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java project\\images\\Customer Registration & Check IN.png")); // NOI18N
        jLabel1.setText("Customer Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 189, 64));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 280, 28));

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 145, 280, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 270, 28));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 270, 31));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 270, 25));

        combogender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 335, 270, 33));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Nationality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 388, 270, 34));

        txtnation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtnation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 260, 34));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Aadhar Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 260, 28));

        txtaadhar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 563, 260, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Check in Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 280, 34));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 280, 32));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Room Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 280, 30));

        combobedtype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combobedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", " " }));
        combobedtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedtypeItemStateChanged(evt);
            }
        });
        combobedtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobedtypeActionPerformed(evt);
            }
        });
        getContentPane().add(combobedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 280, 36));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Bed Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 280, 28));

        comboroomtype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC", " ", " " }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        comboroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboroomtypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 280, 36));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Room Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 280, 28));

        comboroomnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(comboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 280, 34));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 280, 36));

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 280, 42));

        btncheckin.setBackground(new java.awt.Color(204, 0, 51));
        btncheckin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncheckin.setText("Chech in Now");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 627, -1, 40));

        btnclear.setBackground(new java.awt.Color(204, 0, 51));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 627, 100, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\java project\\images\\bac.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1110, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
    if(txtname.getText().equals("")){
      JOptionPane.showMessageDialog(this, "All Field is Requied");
      txtname.requestFocus();
    }
    else if(txtmobile.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       txtmobile.requestFocus();
    }
    
    else if(txtnation.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       txtnation.requestFocus();
    }
    else if(txtaadhar.getText().equals("")){
      JOptionPane.showMessageDialog(this, "All Field is Requied");
      txtaadhar.requestFocus();
    }
    
    else if(txtmobile.getText().length()!=10){
        JOptionPane.showMessageDialog(this, "Mobile Number Should be 10 Digit.");
    }
    else if(txtaadhar.getText().length()!=12){
        JOptionPane.showMessageDialog(this, "Adhar Number Should be 12 Digit.");
    }
    else{
        try {
            pst=con.prepareStatement("insert into customer(name,mobile,gender,id,nationality,indate,Room_Number,Room_Type,Bed_Type,price,status)values(?,?,?,?,?,?,?,?,?,?,?)");
           
            pst.setString(1, txtname.getText());
            pst.setString(2, txtmobile.getText());
         
            pst.setString(3, combogender.getItemAt(combogender.getSelectedIndex()));
               
            pst.setString(4, txtaadhar.getText());
            pst.setString(5, txtnation.getText());
            pst.setString(6, txtdate.getText());
            pst.setString(7, (String) comboroomnumber.getSelectedItem());
            pst.setString(8,(String) combobedtype.getSelectedItem());
            pst.setString(9, (String) comboroomtype.getSelectedItem());
            pst.setString(10, txtprice.getText());
            pst.setString(11,"NULL");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Customer checked sucessfully");
            txtname.setText("");
            txtmobile.setText("");
            txtnation.setText("");
            txtaadhar.setText("");
            pst=con.prepareStatement("update room set status=? where Room_Number=?");
            pst.setString(1,"Booked" );
            pst.setString(2, (String) comboroomnumber.getSelectedItem());
            pst.executeUpdate();
            gowtham();
            }catch (SQLException ex) {
        Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    





        // TODO add your handling code here:
    }//GEN-LAST:event_btncheckinActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
txtaadhar.setText("");
txtmobile.setText("");
txtname.setText("");
txtnation.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void comboroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboroomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combobedtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedtypeItemStateChanged
gowtham();        // TODO add your handling code here:
    }//GEN-LAST:event_combobedtypeItemStateChanged

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
gowtham();        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void combobedtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobedtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobedtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                boolean name = true;
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> combobedtype;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomnumber;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtaadhar;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnation;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
